spring:
  application:
    name: Alles op Kamp
  profiles:
    active: ${ENV:local},${USERNAME:_ignored_}

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
