spring:
  application:
    name: Alles op Kamp
  datasource:
    url: ${DATABASE_JDBC}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration