name: Java CI with Maven Wrapper

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: build-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  JAVA_VERSION: '22'

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up JDK
        uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven Wrapper
        run: ./mvnw clean verify --file pom.xml --fail-at-end --update-snapshots

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create docker image
        if: ${{ !github.head_ref }}
        run: ./mvnw spring-boot:build-image -Pproduction -DskipTests -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}/alles-op-kamp:${{ github.sha }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/alles-op-kamp:${{ github.sha }}