name: Heroku deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        description: "deployment environment"
        default: "tst"
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "tst"

concurrency:
  group: deploy-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Setup flyctl
        uses: superfly/flyctl-actions@1.5

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} --app ${{ secrets.FLY_APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}